"""add event system tables

Revision ID: 1aaa35402c10
Revises: 558ad568695e
Create Date: 2026-04-15 13:52:20.229772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aaa35402c10'
down_revision: Union[str, Sequence[str], None] = '558ad568695e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.Enum('SINGLES_ELIMINATION', 'DOUBLES_ELIMINATION', 'ROUND_ROBIN', name='eventtype'), nullable=False),
    sa.Column('min_ntrp', sa.String(length=10), nullable=False),
    sa.Column('max_ntrp', sa.String(length=10), nullable=False),
    sa.Column('gender_requirement', sa.String(length=20), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('games_per_set', sa.Integer(), nullable=False),
    sa.Column('num_sets', sa.Integer(), nullable=False),
    sa.Column('match_tiebreak', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_fee', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('match_order', sa.Integer(), nullable=False),
    sa.Column('player_a_id', sa.UUID(), nullable=True),
    sa.Column('player_b_id', sa.UUID(), nullable=True),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('group_name', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'CONFIRMED', 'DISPUTED', 'WALKOVER', name='eventmatchstatus'), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_a_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_b_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=10), nullable=True),
    sa.Column('team_name', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'CONFIRMED', 'WITHDRAWN', 'ELIMINATED', name='eventparticipantstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_participants_event_user')
    )
    op.create_table('event_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('tiebreak_a', sa.Integer(), nullable=True),
    sa.Column('tiebreak_b', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['event_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'set_number', name='uq_event_sets_match_set')
    )
    op.add_column('chat_rooms', sa.Column('event_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'chat_rooms', ['event_id'])
    op.create_foreign_key(None, 'chat_rooms', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.drop_constraint(None, 'chat_rooms', type_='unique')
    op.drop_column('chat_rooms', 'event_id')
    op.drop_table('event_sets')
    op.drop_table('event_participants')
    op.drop_table('event_matches')
    op.drop_table('events')
    # ### end Alembic commands ###
