"""add blocks, reports tables and is_suspended

Revision ID: 1d100ee70732
Revises: b1a8e8d1881b
Create Date: 2026-04-14 20:45:00.682187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d100ee70732'
down_revision: Union[str, Sequence[str], None] = 'b1a8e8d1881b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_blocks_blocker_blocked')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('USER', 'REVIEW', name='reporttargettype'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('NO_SHOW', 'HARASSMENT', 'FALSE_INFO', 'INAPPROPRIATE', 'OTHER', name='reportreason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', name='reportstatus'), nullable=False),
    sa.Column('resolution', sa.Enum('DISMISSED', 'WARNED', 'CONTENT_HIDDEN', 'SUSPENDED', name='reportresolution'), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'target_type', 'target_id', name='uq_reports_reporter_target')
    )
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_suspended')
    op.drop_table('reports')
    op.drop_table('blocks')
    # ### end Alembic commands ###
