"""add admin_audit_log table

Revision ID: ad9eb4a45eaa
Revises: 1aaa35402c10
Create Date: 2026-04-15 14:49:14.231838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9eb4a45eaa'
down_revision: Union[str, Sequence[str], None] = '1aaa35402c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('USER_SUSPENDED', 'USER_UNSUSPENDED', 'USER_ROLE_CHANGED', 'USER_CREDIT_RESET', 'COURT_APPROVED', 'COURT_REJECTED', 'COURT_DELETED', 'REPORT_RESOLVED', 'BOOKING_CANCELLED', 'EVENT_CANCELLED', 'EVENT_PARTICIPANT_REMOVED', 'MESSAGE_DELETED', name='adminaction'), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
